### ISSUE TITLE
Give us a Kodi Omega version and we'll sacrifice our first borns

### ISSUE THREAD

**Issue by cg00001** [mistervee/skin.madnox#55]
This awesome skin needs a Kodi Omega version -please.
Don't forget Omega will need from next version:
`<import addon="xbmc.gui" version="5.17.0"/>`

**Comment by meowmoo** [comment]
Keep your hopes low
Mr V hasn't been around for a few years

**Comment by gibxxi** [comment]
> This awesome skin needs a Kodi Omega version -please. Don't forget Omega will need from next version: `<import addon="xbmc.gui" version="5.17.0"/>`

If you wish to risk issues with the skin in it's current form, you can bump the relevant lines in the addon.xml file so that it will load within Kodi v21 - Omega, but there were outstanding bugs / issues with this skin, even under 'Matrix' (which is the last time Mr.V actively worked on it), so expect problems going forwards.

As Meowmoo has already stated, it's been quite a long time since Mr.V was last seen. Either on here or on the Kodi forums, so I wouldn't expect any progress on this unless somebody else decides to take up the baton, to move the skin forwards, in all honesty.

**Comment by Fietspomp86** [comment]
> > This awesome skin needs a Kodi Omega version -please. Don't forget Omega will need from next version: `<import addon="xbmc.gui" version="5.17.0"/>`
> 
> If you wish to risk issues with the skin in it's current form, you can bump the relevant lines in the addon.xml file so that it will load within Kodi v21 - Omega, but there were outstanding bugs / issues with this skin, even under 'Matrix' (which is the last time Mr.V actively worked on it), so expect problems going forwards.
> 
> As Meowmoo has already stated, it's been quite a long time since Mr.V was last seen. Either on here or on the Kodi forums, so I wouldn't expect any progress on this unless somebody else decides to take up the baton, to move the skin forwards, in all honesty.

I just did this, using latest Libreelec Nightly, [LibreELEC-Generic-legacy.x86_64-12.0-nightly-20231217](https://test.libreelec.tv/12.0/Generic/Generic-legacy/LibreELEC-Generic-legacy.x86_64-12.0-nightly-20231217-1833aee.img.gz) seems to working fine so far!
Only adjusted the line in addon.xml.

Will continue testing and revert here with findings.

Would be very nice if we can keep this skin alive!

EDIT: I see there is a fork, which was active not that long ago ( 8 months).
Also some commits have been made I see.
Here is the fork: https://github.com/FrAcTi0N/skin.madnox

Not sure if we can reach out/tag him/her, perhaps that is a way forward?
